import { ThemeProvider } from "@mui/material/styles";
import "./globals.css";
import { Inter } from "next/font/google";
import { theme } from "@/constant/theme";
import StyledComponentsRegistry from "./lib/registry";
import { Provider} from "react-redux";
import { store } from "@/redux/store";
import { JobDataProvider } from "@/context/JobDataContext";
import { SavedJobProvider } from "@/context/SavedJobContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Provider store={store}> */}
              <SavedJobProvider>

      <JobDataProvider>
        <StyledComponentsRegistry>
          <ThemeProvider theme={theme}>
            {children}
            </ThemeProvider>
        </StyledComponentsRegistry>
                    {/* </Provider> */}

</JobDataProvider></SavedJobProvider>
      </body>
    </html>
  )}